version: "1"
rules:
  - base: "master"
    upstream: master
    mergeMethod: merge
    reviewers:
      - yelizariev
  - base: "14.0"
    upstream: odoo:14.0
    mergeMethod: merge
    reviewers:
      - yelizariev
  - base: "13.0"
    upstream: odoo:13.0
    mergeMethod: merge
    reviewers:
      - yelizariev
  - base: "12.0"
    upstream: odoo:12.0
    mergeMethod: merge
    reviewers:
      - yelizariev
  - base: "11.0"
    upstream: odoo:11.0
    mergeMethod: merge
    reviewers:
      - yelizariev
label: ":alien: pull from odoo" 
