version: "1"
rules:
  - base: "14.0"
    upstream: odoo:14.0
    mergeMethod: merge
  - base: "13.0"
    upstream: odoo:13.0
    mergeMethod: merge
  - base: "12.0"
    upstream: odoo:12.0
    mergeMethod: merge
  - base: "11.0"
    upstream: odoo:11.0
    mergeMethod: merge
label: ":alien: pull from odoo" 
